### PR TITLE
add INTERCAL.i

### PR DESCRIPTION
**Pull request by vivekashok1221**

### CODE REVIEW

**Review by Den4200 — CHANGES_REQUESTED** [review]
Your code does not print "Hello, world!". Please fix that.

**Comment by vivekashok1221** [comment]
Now that's embarrassing.
What output did you get, how was it lacking?

**Comment by Den4200** [comment]
Hmm, apologies. I must've copied the code wrong the first time, it seems to work now. Could you change the filename to be all lowercase though? GitHub messes up the ordering if one is not the same casing as the others.

**Comment by vivekashok1221** [comment]
Sure.

**Review by Den4200 — APPROVED** [review]
Thanks!

**Pull request merged**
