### PR TITLE
Add Pascal implementation

### LINKED ISSUE #1: Hello, world!
## Description
We need more implementations in different languages of "**Hello, world!**". Feel free to create pull requests for other computer languages!

- Name the file(s) with the language name, e.g. `rust.rs`
- Make sure to add the language(s) of your implementation(s) to the list in `README.md` in alphabetical order with a link to the corresponding file, like this:
```md
- [Rust](rust.rs)
```

Happy coding!

<hr>

image

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Den4200 — CHANGES_REQUESTED** [review]
Could you add `Pascal` to the implementation list in alphabetical order?

**Comment by ghost** [comment]
> Could you add `Pascal` to the implementation list in alphabetical order?

yes, sure

**Comment by Den4200** [comment]
Please make sure it's in alphabetical order!

**Comment by ghost** [comment]
> Please make sure it's in alphabetical order!

I changed it

**Review by Den4200 — APPROVED** [review]
Looks good now, thank you!

**Pull request merged**
